import { Team, Region } from '@/types';

// 2026 NCAA Tournament - All 68 teams with KenPom stats
// First Four play-in teams included (marked with isPlayIn: true in matchup data)
export const TEAMS_2026: Team[] = [
  // ===================== EAST REGION =====================
  {
    id: 'duke',
    name: 'Duke',
    seed: 1,
    region: 'East',
    conference: 'ACC',
    programTier: 'blueblood',
    isCinderella: false,
    record: '32-2',
    kenpom: { rank: 1, adjEM: 38.88, adjO: 126.5, adjD: 87.6, adjT: 72.4, luck: 0.023, sos: 4 },
  },
  {
    id: 'uconn',
    name: 'UConn',
    seed: 2,
    region: 'East',
    conference: 'Big East',
    programTier: 'blueblood',
    isCinderella: false,
    record: '28-6',
    kenpom: { rank: 6, adjEM: 29.88, adjO: 121.4, adjD: 91.5, adjT: 70.3, luck: -0.018, sos: 10 },
  },
  {
    id: 'michigan-state',
    name: 'Michigan State',
    seed: 3,
    region: 'East',
    conference: 'Big Ten',
    programTier: 'blueblood',
    isCinderella: false,
    record: '27-7',
    kenpom: { rank: 9, adjEM: 30.45, adjO: 119.3, adjD: 88.8, adjT: 71.2, luck: -0.005, sos: 7 },
  },
  {
    id: 'kansas',
    name: 'Kansas',
    seed: 4,
    region: 'East',
    conference: 'Big 12',
    programTier: 'blueblood',
    isCinderella: false,
    record: '25-9',
    kenpom: { rank: 15, adjEM: 26.73, adjO: 118.7, adjD: 92.0, adjT: 70.6, luck: 0.014, sos: 6 },
  },
  {
    id: 'st-johns',
    name: "St. John's",
    seed: 5,
    region: 'East',
    conference: 'Big East',
    programTier: 'power_conference',
    isCinderella: false,
    record: '26-8',
    kenpom: { rank: 19, adjEM: 24.11, adjO: 117.2, adjD: 93.1, adjT: 69.8, luck: 0.021, sos: 12 },
  },
  {
    id: 'louisville',
    name: 'Louisville',
    seed: 6,
    region: 'East',
    conference: 'ACC',
    programTier: 'blueblood',
    isCinderella: false,
    record: '24-10',
    kenpom: { rank: 24, adjEM: 22.34, adjO: 115.8, adjD: 93.4, adjT: 68.3, luck: -0.012, sos: 15 },
  },
  {
    id: 'ucla',
    name: 'UCLA',
    seed: 7,
    region: 'East',
    conference: 'Big Ten',
    programTier: 'blueblood',
    isCinderella: false,
    record: '22-12',
    kenpom: { rank: 28, adjEM: 20.87, adjO: 114.4, adjD: 93.5, adjT: 73.1, luck: -0.027, sos: 9 },
  },
  {
    id: 'ohio-state',
    name: 'Ohio State',
    seed: 8,
    region: 'East',
    conference: 'Big Ten',
    programTier: 'power_conference',
    isCinderella: false,
    record: '22-13',
    kenpom: { rank: 33, adjEM: 18.92, adjO: 112.7, adjD: 93.8, adjT: 70.9, luck: 0.008, sos: 11 },
  },
  {
    id: 'tcu',
    name: 'TCU',
    seed: 9,
    region: 'East',
    conference: 'Big 12',
    programTier: 'power_conference',
    isCinderella: false,
    record: '21-13',
    kenpom: { rank: 36, adjEM: 17.45, adjO: 111.3, adjD: 93.8, adjT: 72.6, luck: 0.016, sos: 8 },
  },
  {
    id: 'ucf',
    name: 'UCF',
    seed: 10,
    region: 'East',
    conference: 'Big 12',
    programTier: 'mid_major',
    isCinderella: false,
    record: '22-11',
    kenpom: { rank: 38, adjEM: 16.88, adjO: 110.9, adjD: 94.0, adjT: 74.3, luck: 0.019, sos: 14 },
  },
  {
    id: 'south-florida',
    name: 'South Florida',
    seed: 11,
    region: 'East',
    conference: 'American',
    programTier: 'mid_major',
    isCinderella: true,
    record: '24-10',
    kenpom: { rank: 52, adjEM: 13.44, adjO: 108.2, adjD: 94.8, adjT: 69.1, luck: 0.038, sos: 28 },
  },
  {
    id: 'northern-iowa',
    name: 'Northern Iowa',
    seed: 12,
    region: 'East',
    conference: 'Missouri Valley',
    programTier: 'mid_major',
    isCinderella: true,
    record: '26-8',
    kenpom: { rank: 44, adjEM: 15.21, adjO: 109.4, adjD: 94.2, adjT: 66.8, luck: 0.029, sos: 35 },
  },
  {
    id: 'cal-baptist',
    name: 'Cal Baptist',
    seed: 13,
    region: 'East',
    conference: 'WAC',
    programTier: 'cinderella',
    isCinderella: true,
    record: '27-7',
    kenpom: { rank: 78, adjEM: 9.33, adjO: 105.1, adjD: 95.7, adjT: 71.5, luck: 0.041, sos: 66 },
  },
  {
    id: 'north-dakota-state',
    name: 'North Dakota State',
    seed: 14,
    region: 'East',
    conference: 'Summit League',
    programTier: 'cinderella',
    isCinderella: true,
    record: '28-6',
    kenpom: { rank: 89, adjEM: 7.88, adjO: 104.0, adjD: 96.1, adjT: 68.4, luck: 0.033, sos: 78 },
  },
  {
    id: 'furman',
    name: 'Furman',
    seed: 15,
    region: 'East',
    conference: 'SoCon',
    programTier: 'cinderella',
    isCinderella: true,
    record: '25-9',
    kenpom: { rank: 118, adjEM: 5.44, adjO: 101.8, adjD: 96.3, adjT: 70.2, luck: 0.022, sos: 94 },
  },
  {
    id: 'siena',
    name: 'Siena',
    seed: 16,
    region: 'East',
    conference: 'MAAC',
    programTier: 'cinderella',
    isCinderella: true,
    record: '25-9',
    kenpom: { rank: 168, adjEM: -1.22, adjO: 98.4, adjD: 99.6, adjT: 69.8, luck: 0.044, sos: 144 },
  },

  // ===================== WEST REGION =====================
  {
    id: 'arizona',
    name: 'Arizona',
    seed: 1,
    region: 'West',
    conference: 'Big 12',
    programTier: 'blueblood',
    isCinderella: false,
    record: '32-2',
    kenpom: { rank: 2, adjEM: 37.60, adjO: 125.3, adjD: 87.7, adjT: 74.2, luck: -0.012, sos: 5 },
  },
  {
    id: 'purdue',
    name: 'Purdue',
    seed: 2,
    region: 'West',
    conference: 'Big Ten',
    programTier: 'power_conference',
    isCinderella: false,
    record: '29-5',
    kenpom: { rank: 8, adjEM: 31.18, adjO: 122.5, adjD: 91.3, adjT: 69.4, luck: 0.017, sos: 9 },
  },
  {
    id: 'gonzaga',
    name: 'Gonzaga',
    seed: 3,
    region: 'West',
    conference: 'WCC',
    programTier: 'power_conference',
    isCinderella: false,
    record: '27-6',
    kenpom: { rank: 11, adjEM: 29.22, adjO: 120.8, adjD: 91.6, adjT: 75.1, luck: 0.028, sos: 22 },
  },
  {
    id: 'arkansas',
    name: 'Arkansas',
    seed: 4,
    region: 'West',
    conference: 'SEC',
    programTier: 'power_conference',
    isCinderella: false,
    record: '24-9',
    kenpom: { rank: 16, adjEM: 25.42, adjO: 117.3, adjD: 91.9, adjT: 72.8, luck: 0.022, sos: 13 },
  },
  {
    id: 'wisconsin',
    name: 'Wisconsin',
    seed: 5,
    region: 'West',
    conference: 'Big Ten',
    programTier: 'power_conference',
    isCinderella: false,
    record: '23-10',
    kenpom: { rank: 20, adjEM: 23.54, adjO: 113.9, adjD: 90.4, adjT: 64.2, luck: 0.011, sos: 10 },
  },
  {
    id: 'byu',
    name: 'BYU',
    seed: 6,
    region: 'West',
    conference: 'Big 12',
    programTier: 'power_conference',
    isCinderella: false,
    record: '23-11',
    kenpom: { rank: 26, adjEM: 21.67, adjO: 116.1, adjD: 94.4, adjT: 71.7, luck: -0.008, sos: 16 },
  },
  {
    id: 'miami-fl',
    name: 'Miami (FL)',
    seed: 7,
    region: 'West',
    conference: 'ACC',
    programTier: 'power_conference',
    isCinderella: false,
    record: '22-11',
    kenpom: { rank: 31, adjEM: 19.33, adjO: 113.2, adjD: 93.9, adjT: 70.4, luck: 0.003, sos: 17 },
  },
  {
    id: 'villanova',
    name: 'Villanova',
    seed: 8,
    region: 'West',
    conference: 'Big East',
    programTier: 'blueblood',
    isCinderella: false,
    record: '21-13',
    kenpom: { rank: 35, adjEM: 17.88, adjO: 112.1, adjD: 94.2, adjT: 67.9, luck: -0.014, sos: 14 },
  },
  {
    id: 'utah-state',
    name: 'Utah State',
    seed: 9,
    region: 'West',
    conference: 'Mountain West',
    programTier: 'mid_major',
    isCinderella: false,
    record: '27-7',
    kenpom: { rank: 34, adjEM: 18.22, adjO: 112.8, adjD: 94.6, adjT: 68.7, luck: 0.024, sos: 31 },
  },
  {
    id: 'missouri',
    name: 'Missouri',
    seed: 10,
    region: 'West',
    conference: 'SEC',
    programTier: 'power_conference',
    isCinderella: false,
    record: '21-12',
    kenpom: { rank: 39, adjEM: 16.54, adjO: 111.6, adjD: 95.1, adjT: 73.8, luck: -0.022, sos: 18 },
  },
  {
    id: 'texas',
    name: 'Texas',
    seed: 11,
    region: 'West',
    conference: 'SEC',
    programTier: 'blueblood',
    isCinderella: false,
    record: '20-15',
    kenpom: { rank: 47, adjEM: 14.77, adjO: 110.3, adjD: 95.5, adjT: 71.1, luck: -0.031, sos: 20 },
  },
  {
    id: 'high-point',
    name: 'High Point',
    seed: 12,
    region: 'West',
    conference: 'Big South',
    programTier: 'cinderella',
    isCinderella: true,
    record: '28-6',
    kenpom: { rank: 46, adjEM: 14.88, adjO: 110.8, adjD: 95.9, adjT: 75.6, luck: 0.035, sos: 42 },
  },
  {
    id: 'hawaii',
    name: "Hawai'i",
    seed: 13,
    region: 'West',
    conference: 'Big West',
    programTier: 'cinderella',
    isCinderella: true,
    record: '26-8',
    kenpom: { rank: 74, adjEM: 10.22, adjO: 106.3, adjD: 96.1, adjT: 72.3, luck: 0.038, sos: 61 },
  },
  {
    id: 'kennesaw-state',
    name: 'Kennesaw State',
    seed: 14,
    region: 'West',
    conference: 'ASUN',
    programTier: 'cinderella',
    isCinderella: true,
    record: '26-8',
    kenpom: { rank: 94, adjEM: 7.11, adjO: 103.4, adjD: 96.3, adjT: 70.9, luck: 0.027, sos: 82 },
  },
  {
    id: 'queens',
    name: 'Queens',
    seed: 15,
    region: 'West',
    conference: 'Atlantic Sun',
    programTier: 'cinderella',
    isCinderella: true,
    record: '24-10',
    kenpom: { rank: 122, adjEM: 4.98, adjO: 101.3, adjD: 96.3, adjT: 71.4, luck: 0.019, sos: 101 },
  },
  {
    id: 'liu',
    name: 'LIU',
    seed: 16,
    region: 'West',
    conference: 'NEC',
    programTier: 'cinderella',
    isCinderella: true,
    record: '24-10',
    kenpom: { rank: 172, adjEM: -2.01, adjO: 97.8, adjD: 99.8, adjT: 70.1, luck: 0.031, sos: 151 },
  },

  // ===================== MIDWEST REGION =====================
  {
    id: 'michigan',
    name: 'Michigan',
    seed: 1,
    region: 'Midwest',
    conference: 'Big Ten',
    programTier: 'blueblood',
    isCinderella: false,
    record: '31-3',
    kenpom: { rank: 3, adjEM: 37.58, adjO: 122.4, adjD: 84.8, adjT: 68.9, luck: 0.043, sos: 6 },
  },
  {
    id: 'iowa-state',
    name: 'Iowa State',
    seed: 2,
    region: 'Midwest',
    conference: 'Big 12',
    programTier: 'power_conference',
    isCinderella: false,
    record: '28-6',
    kenpom: { rank: 6, adjEM: 32.37, adjO: 116.8, adjD: 84.4, adjT: 68.7, luck: -0.009, sos: 8 },
  },
  {
    id: 'virginia',
    name: 'Virginia',
    seed: 3,
    region: 'Midwest',
    conference: 'ACC',
    programTier: 'blueblood',
    isCinderella: false,
    record: '26-8',
    kenpom: { rank: 12, adjEM: 28.87, adjO: 112.3, adjD: 83.4, adjT: 62.1, luck: 0.019, sos: 11 },
  },
  {
    id: 'alabama',
    name: 'Alabama',
    seed: 4,
    region: 'Midwest',
    conference: 'SEC',
    programTier: 'power_conference',
    isCinderella: false,
    record: '26-8',
    kenpom: { rank: 14, adjEM: 27.54, adjO: 119.4, adjD: 91.8, adjT: 75.8, luck: -0.033, sos: 14 },
  },
  {
    id: 'texas-tech',
    name: 'Texas Tech',
    seed: 5,
    region: 'Midwest',
    conference: 'Big 12',
    programTier: 'power_conference',
    isCinderella: false,
    record: '24-10',
    kenpom: { rank: 18, adjEM: 24.88, adjO: 115.4, adjD: 90.5, adjT: 66.3, luck: 0.007, sos: 7 },
  },
  {
    id: 'tennessee',
    name: 'Tennessee',
    seed: 6,
    region: 'Midwest',
    conference: 'SEC',
    programTier: 'power_conference',
    isCinderella: false,
    record: '23-11',
    kenpom: { rank: 22, adjEM: 23.11, adjO: 114.6, adjD: 91.5, adjT: 67.8, luck: -0.019, sos: 12 },
  },
  {
    id: 'kentucky',
    name: 'Kentucky',
    seed: 7,
    region: 'Midwest',
    conference: 'SEC',
    programTier: 'blueblood',
    isCinderella: false,
    record: '21-13',
    kenpom: { rank: 27, adjEM: 21.14, adjO: 115.7, adjD: 94.6, adjT: 73.2, luck: -0.028, sos: 15 },
  },
  {
    id: 'georgia',
    name: 'Georgia',
    seed: 8,
    region: 'Midwest',
    conference: 'SEC',
    programTier: 'power_conference',
    isCinderella: false,
    record: '20-14',
    kenpom: { rank: 37, adjEM: 17.22, adjO: 111.4, adjD: 94.2, adjT: 71.8, luck: 0.012, sos: 16 },
  },
  {
    id: 'saint-louis',
    name: 'Saint Louis',
    seed: 9,
    region: 'Midwest',
    conference: 'A-10',
    programTier: 'mid_major',
    isCinderella: false,
    record: '24-9',
    kenpom: { rank: 40, adjEM: 16.33, adjO: 110.8, adjD: 94.5, adjT: 67.4, luck: 0.021, sos: 38 },
  },
  {
    id: 'santa-clara',
    name: 'Santa Clara',
    seed: 10,
    region: 'Midwest',
    conference: 'WCC',
    programTier: 'mid_major',
    isCinderella: true,
    record: '24-10',
    kenpom: { rank: 48, adjEM: 14.44, adjO: 109.7, adjD: 95.3, adjT: 70.6, luck: 0.028, sos: 44 },
  },
  {
    id: 'smu',
    name: 'SMU',
    seed: 11,
    region: 'Midwest',
    conference: 'ACC',
    programTier: 'power_conference',
    isCinderella: false,
    record: '21-14',
    kenpom: { rank: 54, adjEM: 13.11, adjO: 108.9, adjD: 95.8, adjT: 72.3, luck: -0.017, sos: 23 },
  },
  {
    id: 'akron',
    name: 'Akron',
    seed: 12,
    region: 'Midwest',
    conference: 'MAC',
    programTier: 'mid_major',
    isCinderella: true,
    record: '25-9',
    kenpom: { rank: 57, adjEM: 12.78, adjO: 108.4, adjD: 95.6, adjT: 69.2, luck: 0.033, sos: 55 },
  },
  {
    id: 'hofstra',
    name: 'Hofstra',
    seed: 13,
    region: 'Midwest',
    conference: 'CAA',
    programTier: 'cinderella',
    isCinderella: true,
    record: '26-7',
    kenpom: { rank: 81, adjEM: 8.97, adjO: 104.8, adjD: 95.8, adjT: 74.1, luck: 0.036, sos: 72 },
  },
  {
    id: 'wright-state',
    name: 'Wright State',
    seed: 14,
    region: 'Midwest',
    conference: 'Horizon',
    programTier: 'cinderella',
    isCinderella: true,
    record: '26-8',
    kenpom: { rank: 96, adjEM: 6.88, adjO: 103.1, adjD: 96.2, adjT: 71.3, luck: 0.029, sos: 84 },
  },
  {
    id: 'tennessee-state',
    name: 'Tennessee State',
    seed: 15,
    region: 'Midwest',
    conference: 'OVC',
    programTier: 'cinderella',
    isCinderella: true,
    record: '22-12',
    kenpom: { rank: 134, adjEM: 3.11, adjO: 100.2, adjD: 97.1, adjT: 72.8, luck: 0.018, sos: 118 },
  },
  {
    id: 'howard',
    name: 'Howard',
    seed: 16,
    region: 'Midwest',
    conference: 'MEAC',
    programTier: 'cinderella',
    isCinderella: true,
    record: '20-13',
    kenpom: { rank: 178, adjEM: -2.88, adjO: 97.1, adjD: 100.0, adjT: 70.4, luck: 0.028, sos: 158 },
  },

  // ===================== SOUTH REGION =====================
  {
    id: 'florida',
    name: 'Florida',
    seed: 1,
    region: 'South',
    conference: 'SEC',
    programTier: 'blueblood',
    isCinderella: false,
    record: '26-7',
    kenpom: { rank: 4, adjEM: 33.75, adjO: 121.2, adjD: 87.4, adjT: 71.3, luck: -0.024, sos: 9 },
  },
  {
    id: 'houston',
    name: 'Houston',
    seed: 2,
    region: 'South',
    conference: 'Big 12',
    programTier: 'power_conference',
    isCinderella: false,
    record: '28-6',
    kenpom: { rank: 5, adjEM: 33.37, adjO: 118.2, adjD: 84.8, adjT: 66.1, luck: 0.015, sos: 7 },
  },
  {
    id: 'illinois',
    name: 'Illinois',
    seed: 3,
    region: 'South',
    conference: 'Big Ten',
    programTier: 'power_conference',
    isCinderella: false,
    record: '27-7',
    kenpom: { rank: 7, adjEM: 32.09, adjO: 123.1, adjD: 91.0, adjT: 73.8, luck: 0.031, sos: 8 },
  },
  {
    id: 'nebraska',
    name: 'Nebraska',
    seed: 4,
    region: 'South',
    conference: 'Big Ten',
    programTier: 'power_conference',
    isCinderella: false,
    record: '24-10',
    kenpom: { rank: 13, adjEM: 27.88, adjO: 118.4, adjD: 90.5, adjT: 70.7, luck: 0.014, sos: 11 },
  },
  {
    id: 'vanderbilt',
    name: 'Vanderbilt',
    seed: 5,
    region: 'South',
    conference: 'SEC',
    programTier: 'power_conference',
    isCinderella: false,
    record: '24-10',
    kenpom: { rank: 17, adjEM: 25.11, adjO: 116.7, adjD: 91.6, adjT: 71.9, luck: -0.006, sos: 13 },
  },
  {
    id: 'north-carolina',
    name: 'North Carolina',
    seed: 6,
    region: 'South',
    conference: 'ACC',
    programTier: 'blueblood',
    isCinderella: false,
    record: '22-12',
    kenpom: { rank: 23, adjEM: 22.77, adjO: 116.3, adjD: 93.5, adjT: 74.8, luck: -0.021, sos: 16 },
  },
  {
    id: 'saint-marys',
    name: "Saint Mary's",
    seed: 7,
    region: 'South',
    conference: 'WCC',
    programTier: 'mid_major',
    isCinderella: false,
    record: '26-7',
    kenpom: { rank: 29, adjEM: 20.44, adjO: 113.8, adjD: 93.4, adjT: 63.8, luck: 0.014, sos: 29 },
  },
  {
    id: 'clemson',
    name: 'Clemson',
    seed: 8,
    region: 'South',
    conference: 'ACC',
    programTier: 'power_conference',
    isCinderella: false,
    record: '21-13',
    kenpom: { rank: 32, adjEM: 19.11, adjO: 112.9, adjD: 93.8, adjT: 69.7, luck: 0.009, sos: 19 },
  },
  {
    id: 'iowa',
    name: 'Iowa',
    seed: 9,
    region: 'South',
    conference: 'Big Ten',
    programTier: 'power_conference',
    isCinderella: false,
    record: '20-14',
    kenpom: { rank: 41, adjEM: 15.88, adjO: 112.6, adjD: 96.7, adjT: 73.4, luck: -0.018, sos: 12 },
  },
  {
    id: 'texas-am',
    name: 'Texas A&M',
    seed: 10,
    region: 'South',
    conference: 'SEC',
    programTier: 'power_conference',
    isCinderella: false,
    record: '21-12',
    kenpom: { rank: 42, adjEM: 15.77, adjO: 111.8, adjD: 96.0, adjT: 70.8, luck: 0.006, sos: 17 },
  },
  {
    id: 'vcu',
    name: 'VCU',
    seed: 11,
    region: 'South',
    conference: 'A-10',
    programTier: 'mid_major',
    isCinderella: true,
    record: '24-10',
    kenpom: { rank: 50, adjEM: 13.88, adjO: 108.6, adjD: 94.7, adjT: 68.4, luck: 0.033, sos: 37 },
  },
  {
    id: 'mcneese',
    name: 'McNeese',
    seed: 12,
    region: 'South',
    conference: 'Southland',
    programTier: 'cinderella',
    isCinderella: true,
    record: '28-6',
    kenpom: { rank: 55, adjEM: 13.02, adjO: 108.1, adjD: 95.1, adjT: 71.6, luck: 0.041, sos: 48 },
  },
  {
    id: 'troy',
    name: 'Troy',
    seed: 13,
    region: 'South',
    conference: 'Sun Belt',
    programTier: 'cinderella',
    isCinderella: true,
    record: '25-9',
    kenpom: { rank: 77, adjEM: 9.44, adjO: 105.3, adjD: 95.9, adjT: 73.2, luck: 0.034, sos: 66 },
  },
  {
    id: 'penn',
    name: 'Penn',
    seed: 14,
    region: 'South',
    conference: 'Ivy League',
    programTier: 'cinderella',
    isCinderella: true,
    record: '23-7',
    kenpom: { rank: 91, adjEM: 7.77, adjO: 104.2, adjD: 96.4, adjT: 67.9, luck: 0.024, sos: 76 },
  },
  {
    id: 'idaho',
    name: 'Idaho',
    seed: 15,
    region: 'South',
    conference: 'Big Sky',
    programTier: 'cinderella',
    isCinderella: true,
    record: '24-9',
    kenpom: { rank: 126, adjEM: 4.33, adjO: 100.8, adjD: 96.5, adjT: 70.3, luck: 0.021, sos: 108 },
  },
  {
    id: 'lehigh',
    name: 'Lehigh',
    seed: 16,
    region: 'South',
    conference: 'Patriot',
    programTier: 'cinderella',
    isCinderella: true,
    record: '22-11',
    kenpom: { rank: 174, adjEM: -1.88, adjO: 97.9, adjD: 99.8, adjT: 68.7, luck: 0.026, sos: 148 },
  },

  // ===================== FIRST FOUR TEAMS (play-in opponents) =====================
  {
    id: 'nc-state',
    name: 'NC State',
    seed: 11,
    region: 'West',
    conference: 'ACC',
    programTier: 'power_conference',
    isCinderella: false,
    record: '19-16',
    kenpom: { rank: 53, adjEM: 13.28, adjO: 109.1, adjD: 95.8, adjT: 70.4, luck: -0.044, sos: 21 },
  },
  {
    id: 'miami-oh',
    name: 'Miami (OH)',
    seed: 11,
    region: 'Midwest',
    conference: 'MAC',
    programTier: 'mid_major',
    isCinderella: false,
    record: '20-15',
    kenpom: { rank: 66, adjEM: 11.44, adjO: 107.3, adjD: 95.9, adjT: 71.8, luck: -0.022, sos: 57 },
  },
  {
    id: 'umbc',
    name: 'UMBC',
    seed: 16,
    region: 'Midwest',
    conference: 'America East',
    programTier: 'cinderella',
    isCinderella: true,
    record: '21-12',
    kenpom: { rank: 182, adjEM: -3.44, adjO: 96.7, adjD: 100.1, adjT: 69.9, luck: 0.019, sos: 162 },
  },
  {
    id: 'prairie-view',
    name: 'Prairie View A&M',
    seed: 16,
    region: 'South',
    conference: 'SWAC',
    programTier: 'cinderella',
    isCinderella: true,
    record: '19-14',
    kenpom: { rank: 188, adjEM: -4.11, adjO: 96.1, adjD: 100.2, adjT: 71.2, luck: 0.011, sos: 174 },
  },
];

export function getTeam(id: string): Team | undefined {
  return TEAMS_2026.find(t => t.id === id);
}

export function getTeamsByRegion(region: Region): Team[] {
  return TEAMS_2026.filter(t => t.region === region && !['nc-state', 'miami-oh', 'umbc', 'prairie-view'].includes(t.id));
}
